import backgroundBlue from './../assets/images/background_blue.png'
import iconQRCode from './../assets/images/icon_QRCode.png'

const Images = {
  backgroundBlue,
  iconQRCode,
  icon_indicator: require('./../assets/images/icon_indicator.png'),
  icon_addBold: require('./../assets/images/icon_addBold.png'),
  imageFingerPrint: require('./../assets/images/img_touchID.png'),
  img_background_button_gradient: require('./../assets/images/img_gradient_button_background.png'),
  noContactImage: require('./../assets/images/img_contact.png'),
  iconHideShowBalance: require('./../assets/images/icon_HideShowBalance.png'),
  backgroundGreen: require('./../assets/images/background_green.png'),
  backgroundOrange: require('./../assets/images/background_orange.png'),
  backgroundBlack: require('./../assets/images/background_black.png'),
  backgroundWhite: require('./../assets/images/background_white.png'),
  imgCardETH: require('./../assets/images/img_card_eth.png'),
  iconQrCode: require('./../assets/images/icon_qr_code.png'),
  iconSend: require('./../assets/images/icon_send.png'),
  iconAdd: require('./../assets/images/icon_add.png'),
  backgroundGrey: require('./../assets/images/background_grey.png'),
  line1: require('./../assets/images/line1.png'),
  line2: require('./../assets/images/line2.png'),
  backButton: require('./../assets/images/icon_back.png'),
  closeButton: require('./../assets/images/icon_close.png'),
  iconETH: require('./../assets/images/icon_eth.png'),
  iconPending: require('./../assets/images/icon_pending.png'),
  iconCopy: require('./../assets/images/icon_copy.png'),
  iconTrash: require('./../assets/images/icon_trash.png'),
  iconEther: require('./../assets/images/icon_eth.png'),
  iconMnemonic: require('./../assets/images/icon_mnemonic.png'),
  iconPrivateKey: require('./../assets/images/wallet_private_key.png'),
  iconAddress: require('./../assets/images/icon_address.png'),
  imgCardCreate: require('./../assets/images/img_card_create.png'),
  imgCardImport: require('./../assets/images/img_card_import.png'),
  iconCloseSearch: require('./../assets/images/icon_clear_text.png'),
  iconScanQRCode: require('./../assets/images/icon_qr_code_2.png'),
  imageSendSuccess: require('./../assets/images/send_success.png'),
  imgChoose: require('./../assets/images/img_choose.png'),
  imgNotChoose: require('./../assets/images/img_not_choose.png'),
  imageBackUp: require('./../assets/images/img_backup.png'),
  imageNoScreenShot: require('./../assets/images/icon_no_screenshot.png'),
  logoStarfish: require('./../assets/images/logo_starfish.png'),
  imgFaceID: require('./../assets/images/icon_face_id.png'),
  imgDeletePin: require('./../assets/images/ic_delete_pin.png'),
  imageThumb: require('./../assets/images/Oval.png'),
  logoGolden: require('./../assets/images/logo_golden.png'),
  logo: require('./../assets/images/logo.png'),
  circleLoading: require('./../assets/images/circle_loading.png'),
  loadingLogo: require('./../assets/images/loading_logo.png'),
  backgroundActionButton: require('./../assets/images/background_action_button.png'),
  backgroundLargeButton: require('./../assets/images/background_large_button.png'),
  hideShowIcon: require('./../assets/images/icon_HideShow.png'),
  iconShow: require('./../assets/images/icon_show.png'),
  iconHide: require('./../assets/images/icon_hide.png'),
  downButton: require('./../assets/images/down_button.png'),
  imgEmptyTransaction: require('./../assets/images/empty_transaction.png'),
  imgLock: require('./../assets/images/img_lock.png'),
  imgTouchID: require('./../assets/images/img_touch_id.png'),
  backgroundCard: require('./../assets/images/background_card.png'),
  createSuccess: require('./../assets/images/create_success.png'),
  iconCheck: require('./../assets/images/icon_check.png'),
  iconLargeAdd: require('./../assets/images/icon_large_add.png'),
  background_add_wallet: require('./../assets/images/background_add_wallet.png'),
  exchangeIcon: require('./../assets/images/ExchangeIcon.png'),
  addressIcon: require('./../assets/images/icon_contact2.png'),
  advanceIcn: require('../assets/images/advance_icon.png'),
  icon_qrcode2: require('../assets/images/qrcode2.png'),
  shimmerToken: require('./../assets/images/shimmer_token.png'),
  iconSync: require('./../assets/images/icon_sync.png'),
  imgScanFrame: require('./../assets/images/img_scan_frame.png'),
  iconAddPhoto: require('./../assets/images/icon_add_photo.png'),
  // iconAddPhoto: require('./../assets/images/icon_add_photo.png'),
  iconFlashOn: require('./../assets/images/ic_flash.png'),
  iconFlashOff: require('./../assets/images/ic_off_flash.png'),
  noWalletImage: require('./../assets/images/img_wallet.png'),
  iconInfo: require('./../assets/images/ic_info.png'),
  backupNoteBook: require('./../assets/images/backup_note_book.png'),
  scanFrame: require('./../assets/images/scan_frame.png'),
  iconDown: require('./../assets/images/icon_down.png'),
  iconUp: require('./../assets/images/icon_up.png'),
  imgEnrase: require('../assets/images/img_enrase.png'),
  iconCollectibles: require('../assets/images/icon_collectible.png'),
  imgEmptyBox: require('../assets/images/empty_box.png'),
  arrowBack: require('../assets/images/arrow_back.png'),
  arrowForward: require('../assets/images/arrow_forward.png'),
  iconRefresh: require('../assets/images/icon_refresh.png')
}

export { Images }
