const GET_STARTED = 'GET_STARTED'
const LOGIN_GOTO = 'LOGIN_GOTO'

const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
const LOGIN_SUCCEED = 'LOGIN_SUCCEED'
const LOGIN_FAILED = 'LOGIN_FAILED'

const REGISTER_REQUESTED = 'REGISTER_REQUESTED'
const REGISTER_SUCCEED = 'REGISTER_SUCCEED'
const REGISTER_FAILED = 'REGISTER_FAILED'

export {
  GET_STARTED,
  LOGIN_GOTO,
  LOGIN_REQUESTED,
  LOGIN_SUCCEED,
  LOGIN_FAILED,
  REGISTER_REQUESTED,
  REGISTER_SUCCEED,
  REGISTER_FAILED
}